/* ══════════════════════════════════════════════
   config.js — Belt topology & routing constants
   Source of truth for all belt metadata.
══════════════════════════════════════════════ */

// ── LTC_HUB_DATA_BEGIN:belts (public build swaps this region — build_public.py/WS4a) ──
/* generated by ltc_truth_synth.py — do not hand-edit.
   NGATE synthetic quiz world (WS4a): every ZIP/SLIC/bay/belt/town is
   fictional; zips come from zero-occupancy blocks of the real zip
   space; the real routing truth never ships. */
const BELT_NAMES = [
  "PD-01 \u00b7 Top White",
  "PD-02 \u00b7 Orange",
  "PD-03 \u00b7 Bottom Green",
  "PD-04 \u00b7 Middle Blue",
  "PD-05 \u00b7 Top Yellow",
  "PD-06 \u00b7 Bottom Yellow",
  "PD-07 \u00b7 Middle White",
  "PD-08 \u00b7 Middle Yellow",
  "PD-09 \u00b7 Middle Black",
  "PD-10 \u00b7 Middle Red",
  "PD-11 \u00b7 Middle Green",
  "PD-12 \u00b7 Top Blue",
  "PD-13 \u00b7 Top Green",
  "Top Black",
  "AF1 \u00b7 Bottom Red",
  "AF2 \u00b7 Top Red"
];

const BELT_COLORS = [
  "#BDBDBD",
  "#E65100",
  "#1B5E20",
  "#1565C0",
  "#F9A825",
  "#F9A825",
  "#BDBDBD",
  "#F9A825",
  "#212121",
  "#C62828",
  "#388E3C",
  "#1565C0",
  "#2E7D32",
  "#212121",
  "#C62828",
  "#C62828"
];

const BELT_FAMILIES = {
  0: [6, 4, 11],
  1: [],
  2: [10, 12, 5],
  3: [11, 6, 7],
  4: [5, 7, 0],
  5: [4, 7, 2],
  6: [0, 3, 7],
  7: [4, 5, 3],
  8: [13, 3, 6],
  9: [14, 15, 3],
  10: [2, 12, 3],
  11: [3, 0, 4],
  12: [2, 10, 0],
  13: [8, 0, 4],
  14: [9, 15, 2],
  15: [9, 14, 0]
};

// No megadest analog in the NGATE world — single-belt lanes only.
const MULTIDEST_BELTS = [];
const MULTIDEST_STATES = [];

const HIGH_MISS_ZONES = [
  {"state": "NH", "slicLow": 8589, "slicHigh": 8589, "note": "MARNH Middle Black \u2014 synthetic drill zone (NGATE)"},
  {"state": "MA", "slicLow": 6989, "slicHigh": 6989, "note": "OREMA Middle Red \u2014 synthetic drill zone (NGATE)"},
  {"state": "ME", "slicLow": 6959, "slicHigh": 6959, "note": "VERME Top Blue \u2014 synthetic drill zone (NGATE)"}
];

const QUIZ_EXCEPTIONS = [
  {"id": "NG1", "note": "Shipper error: NY address with MA ZIP \u2014 synthetic (NGATE)", "routingState": "MA", "prefixStart": 698, "prefixEnd": 698, "zipState": "NY", "city": "EASVVALE", "zipPrefixes": ["715"], "belt": 11},
  {"id": "NG2", "note": "Shipper error: CT address with ME ZIP \u2014 synthetic (NGATE)", "routingState": "ME", "prefixStart": 695, "prefixEnd": 695, "zipState": "CT", "city": "NARVWORTH", "zipPrefixes": ["632"], "belt": 4}
];

const AIR_SORT_RULES = [
  {"service": "UPS NEXT DAY AIR", "serviceCode": "NDA", "level": "1", "prefixMin": "120", "belt": 14},
  {"service": "UPS NEXT DAY AIR EARLY A.M.", "serviceCode": "NDA_EARLY", "level": "1", "aliases": ["NDAEARLY"], "belt": 14},
  {"service": "UPS 2ND DAY AIR", "serviceCode": "2DA_SAT", "level": "2", "satNote": true, "aliases": ["2S", "2DAY SATURDAY COMMITTED"], "belt": 14},
  {"service": "INTERNATIONAL", "serviceCode": "INTL", "intl": true, "aliases": ["INTERNATIONAL"], "belt": 14},
  {"service": "UPS 2ND DAY AIR", "serviceCode": "2DA", "level": "2", "prefixMin": "310", "belt": 15},
  {"service": "UPS 3 DAY SELECT", "serviceCode": "3DA", "level": "3", "aliases": ["3DS"], "prefixMin": "410", "belt": 15}
];

// ── LTC_HUB_DATA_END:belts ──

function _normAirServiceCode(code) {
  return String(code || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
}

function _airServiceMatches(rule, serviceCode) {
  const code = _normAirServiceCode(serviceCode);
  const aliases = [rule.serviceCode].concat(rule.aliases || []);
  return aliases.some(alias => _normAirServiceCode(alias) === code);
}

function _airRuleMatchesEntry(rule, entry) {
  if (!entry || !entry.zip) return false;
  const zip = String(entry.zip).padStart(5, '0');
  const prefix3 = zip.slice(0, 3);
  if (rule.stateFilter && !rule.stateFilter.includes(entry.state)) return false;
  if (rule.prefixFilter && !zip.startsWith(rule.prefixFilter)) return false;
  if (rule.prefixList && !rule.prefixList.some(p => zip.startsWith(p))) return false;
  if (rule.prefixMin && prefix3 < String(rule.prefixMin)) return false;
  if (rule.prefixMax && prefix3 > String(rule.prefixMax)) return false;
  return true;
}

function resolveAirSort(entryOrZip, serviceCode) {
  const entry = typeof entryOrZip === 'string'
    ? { zip: entryOrZip, state: '' }
    : (entryOrZip || {});
  const rule = AIR_SORT_RULES.find(r =>
    _airServiceMatches(r, serviceCode) && _airRuleMatchesEntry(r, entry));
  if (!rule) return null;
  return {
    serviceCode: rule.serviceCode,
    service: rule.service,
    belt: rule.belt,
    beltName: BELT_NAMES[rule.belt],
    level: rule.level || null,
    intl: !!rule.intl,
    satNote: !!rule.satNote,
  };
}

// Real-label variants for international imports (see assets/nda-label.png,
// assets/2da-label.png) — picked at random when an INTL question is built.
const INTL_LABEL_VARIANTS = [
  { service: 'UPS SAVER',     level: '1P' },
  { service: 'UPS EXPEDITED', level: '2'  },
];

// Default passwords — can be overridden by Admin via system_config
const DEFAULT_SUPERVISOR_PASSWORD = 'twi';
const DEFAULT_ADMIN_PASSWORD      = 'admin';

// ── LTC_HUB_DATA_BEGIN:admin (public build swaps this region) ──
/* generated by ltc_truth_synth.py — do not hand-edit.
   NGATE synthetic quiz world (WS4a): every ZIP/SLIC/bay/belt/town is
   fictional; zips come from zero-occupancy blocks of the real zip
   space; the real routing truth never ships. */
// Synthetic training admin — IDs sit in the roster's zero-occupancy block.
const ADMIN_IDS = {
  "2411111": "Training Admin"
};

const EASTER_EGG_ID  = "2422222";
const EASTER_EGG_MSG = "Nice try.";

// ── LTC_HUB_DATA_END:admin ──

// ── LTC_HUB_DATA_BEGIN:service (public build swaps this region) ──
/* generated by ltc_truth_synth.py — do not hand-edit.
   NGATE synthetic quiz world (WS4a): every ZIP/SLIC/bay/belt/town is
   fictional; zips come from zero-occupancy blocks of the real zip
   space; the real routing truth never ships. */
// Service-level overrides (override ZIP routing entirely)
const SERVICE_OVERRIDES = {
  "NDA": {"belt": 14, "name": "AF1 \u00b7 Bottom Red", "note": "Ups Next Day Air 120xx+"},
  "NDA_EARLY": {"belt": 14, "name": "AF1 \u00b7 Bottom Red", "note": "Ups Next Day Air Early A.M."},
  "NDAEARLY": {"belt": 14, "name": "AF1 \u00b7 Bottom Red", "note": "Ups Next Day Air Early A.M."},
  "2DA_SAT": {"belt": 14, "name": "AF1 \u00b7 Bottom Red", "note": "Ups 2Nd Day Air"},
  "2S": {"belt": 14, "name": "AF1 \u00b7 Bottom Red", "note": "Ups 2Nd Day Air"},
  "INTL": {"belt": 14, "name": "AF1 \u00b7 Bottom Red", "note": "International"},
  "INTERNATIONAL": {"belt": 14, "name": "AF1 \u00b7 Bottom Red", "note": "International"},
  "2DA": {"belt": 15, "name": "AF2 \u00b7 Top Red", "note": "Ups 2Nd Day Air 310xx+"},
  "3DA": {"belt": 15, "name": "AF2 \u00b7 Top Red", "note": "Ups 3 Day Select 410xx+"},
  "3DS": {"belt": 15, "name": "AF2 \u00b7 Top Red", "note": "Ups 3 Day Select 410xx+"}
};

// ── LTC_HUB_DATA_END:service ──

// Helper: split belt code and name from "PD-XX · Description"
function beltCode(idx) {
  const name = BELT_NAMES[idx] || '';
  return name.split(' · ')[0] || name;
}
function beltDesc(idx) {
  const name = BELT_NAMES[idx] || '';
  return name.split(' · ')[1] || '';
}
