"""WS4b: the demo-mode replay bundle packager — emit_hub_corpus.pack_replay_bundle.

DEMO_MODE_DESIGN.md fixes the contract: one self-contained JS file assigning
window.DEMO_REPLAY = {hub, label, sortDate, generated, pulls:[{name,csv}...]},
loaded via <script src> (file://-safe, no fetch). The packager reads the
committed dist/ngate-demo/replay/ (manifest + CSVs) so it runs corpus-free and
stdlib-only. Skips when the bundle isn't present (fresh clone without dist).
"""

import importlib.util
import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

GEN = Path(__file__).resolve().parents[1]
REPLAY = GEN / "dist/ngate-demo/replay"
PROFILE = GEN / "world/hub_profile.northgate.json"
EMITTER = GEN / "emit_hub_corpus.py"

# The production live-CSV filename grammar the tracker's _parseFilenameIdx routes on.
FNAME_RE = re.compile(r"_(\d{4})-(\d{2})-(\d{2})_(\d{6})\.csv$")


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _payload(js_text):
    """Extract and parse the window.DEMO_REPLAY object from the bundle JS."""
    marker = "window.DEMO_REPLAY = "
    start = js_text.index(marker) + len(marker)
    body = js_text[start:].strip()
    assert body.endswith(";"), "bundle must end with a ; terminated assignment"
    return json.loads(body[:-1])


@unittest.skipUnless(REPLAY.exists() and (REPLAY / "manifest.json").exists(),
                     "NGATE demo bundle not present")
class DemoReplayBundleTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.mod = _load("emit_hub_corpus", EMITTER)
        cls.profile = json.loads(PROFILE.read_text())
        cls.manifest = json.loads((REPLAY / "manifest.json").read_text())
        cls.js = cls.mod.pack_replay_bundle(REPLAY, cls.profile)
        cls.payload = _payload(cls.js)

    def test_bundle_is_marked_generated_and_parses_as_one_assignment(self):
        self.assertTrue(self.js.startswith("// generated by emit_hub_corpus.py"),
                        "bundle must carry the do-not-hand-edit provenance line")
        self.assertEqual(
            set(self.payload.keys()),
            {"hub", "label", "sortDate", "generated", "pulls"})

    def test_identity_fields_come_from_world_not_hardcode(self):
        self.assertEqual(self.payload["hub"], self.profile["identity"]["hub_code"])
        self.assertIn(self.profile["identity"]["site"], self.payload["label"])
        self.assertIn("synthetic", self.payload["label"].lower())
        self.assertEqual(self.payload["sortDate"], self.manifest["sort_date"])

    def test_pulls_are_flat_manifest_ordered_and_complete(self):
        expected = [f for p in self.manifest["pulls"] for f in p["files"]]
        self.assertEqual([e["name"] for e in self.payload["pulls"]], expected)

    def test_every_name_matches_the_live_feed_filename_grammar(self):
        prefix = self.profile["identity"]["file_prefix"] + "_"
        stamps = []
        for entry in self.payload["pulls"]:
            self.assertTrue(entry["name"].startswith(prefix), entry["name"])
            m = FNAME_RE.search(entry["name"])
            self.assertIsNotNone(m, f"filename grammar violated: {entry['name']}")
            stamps.append(m.group(4))
        self.assertEqual(stamps, sorted(stamps),
                         "pull files must be chronological (HHMMSS non-decreasing)")

    def test_csv_payloads_are_byte_identical_to_the_committed_dist(self):
        for entry in self.payload["pulls"]:
            disk = (REPLAY / entry["name"]).read_bytes().decode("utf-8")
            self.assertEqual(entry["csv"], disk,
                             f"bundle csv drifted from dist for {entry['name']}")
            self.assertIn("\r\n", entry["csv"],
                          "production live CSVs are CRLF; translation detected")

    def test_csv_headers_equal_the_emitter_contract(self):
        hub_hdr = ",".join(self.mod.HUB_HEADER)
        emp_hdr = ",".join(self.mod.EMP_HEADER)
        for entry in self.payload["pulls"]:
            first = entry["csv"].lstrip("﻿").split("\r\n", 1)[0]
            if "_hub_summary_" in entry["name"]:
                self.assertEqual(first, hub_hdr, entry["name"])
            elif "_employee_summary_" in entry["name"]:
                self.assertEqual(first, emp_hdr, entry["name"])

    def test_size_budget(self):
        n = len(self.js.encode("utf-8"))
        self.assertLess(n, 5 * 1024 * 1024, "design size budget is ~5 MB")
        self.assertGreater(n, 100 * 1024, "suspiciously small bundle")

    def test_pack_is_deterministic(self):
        again = self.mod.pack_replay_bundle(REPLAY, self.profile)
        self.assertEqual(self.js, again)

    def test_cli_pack_bundle_writes_the_same_bytes_corpus_free(self):
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "ngate_replay_bundle.js"
            proc = subprocess.run(
                [sys.executable, str(EMITTER), "--pack-bundle",
                 "--bundle-out", str(out)],
                text=True, capture_output=True)
            self.assertEqual(proc.returncode, 0, proc.stderr[-2000:])
            self.assertEqual(out.read_text(encoding="utf-8"), self.js)


if __name__ == "__main__":
    unittest.main()
